language: python
python:
  - "3.5"
  - "3.6"
before_install:
  - pip install -U -r requirements.txt
install:
  - python setup.py install
script:
  - pytest --cov=tablecloth tablecloth
after_success:
  - codecov
