language: python
python:
  - "3.5"
  - "3.6"
before_install:
  - pip install -U -r requirements.txt
install:
  - python setup.py install
script:
  - |
    pytest --cov=tablecloth.queryspace \
    tablecloth/test*.py
after_success:
  - codecov
